~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bE1-HD2.cds.fa -o Pst_bE1-HD2.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bE4-HD2.cds.fa -o Pst_bE4-HD2.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bE6-HD2.cds.fa -o Pst_bE6-HD2.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bE7-HD2.cds.fa -o Pst_bE7-HD2.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bE8-HD2.cds.fa -o Pst_bE8-HD2.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bE9-HD2.cds.fa -o Pst_bE9-HD2.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bW4-HD1.cds.fa -o Pst_bW4-HD1.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bW6-HD1.cds.fa -o Pst_bW6-HD1.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bW7-HD1.cds.fa -o Pst_bW7-HD1.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bW8-HD1.cds.fa -o Pst_bW8-HD1.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bW9-HD1.cds.fa -o Pst_bW9-HD1.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bE1-1HD2.cds.fa -o Pst_bE1-1HD2.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bE2-HD2.cds.fa -o Pst_bE2-HD2.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bE3-HD2.cds.fa -o Pst_bE3-HD2.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bE5-HD2.cds.fa -o Pst_bE5-HD2.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bW2-HD1.cds.fa -o Pst_bW2-HD1.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bW3-HD1.cds.fa -o Pst_bW3-HD1.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bW5-HD1.cds.fa -o Pst_bW5-HD1.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bW1-HD1.cds.fa -o Pst_bW1-HD1.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_bW1-1HD1.cds.fa -o Pst_bW1-1HD1.cds.sig
~/conda_envs/smash/bin/sourmash sketch dna -p k=21,scaled=10 Pst_STE3.cds.fa -o Pst_STE3.cds.sig
